### ISSUE TITLE
loading worker code with ?noworker=yes requires .js suffix

### ISSUE THREAD

**Issue by Pike** [c9/c9.ide.language#2] opened 2015-03-06 12:41 UTC
There's an odd difference in how code is loaded in the worker, depending on whether it's the actual worker or not.

If I start with noworker=yes, I need to provide the full filename, if I use the worker, I can't specify the full file name.
That means that I need to edit the references to js code in my plugin and my worker each time I switch between noworker and not.

**Comment by nightwing** [comment] 2015-03-06 22:05
Worker, main process, and the packed version all use different versions of require so there may be some inconsistencies.
Could you please show an example of the code for which this doesn't work? I couldn't reproduce this with c9 plugins.

**Comment by Pike** [comment] 2015-03-06 22:15
In https://github.com/aisle-moz/moz.xliff, https://github.com/aisle-moz/moz.xliff/blob/master/plugin.js#L16 and https://github.com/aisle-moz/moz.xliff/blob/master/xliff.js#L10

The caveat seems to be relative imports.

**Comment by lennartcl** [comment] 2015-03-09 13:40
Note that this option was introduced for debugging before Chrome would allow workers to be debugged in a sensible way. So at least when using Chrome, there is little use case left for this option. (But I'm guessing you're using Firefox, @Pike :wink:)

**Comment by nightwing** [comment] 2015-03-14 12:59
@Pike https://github.com/c9/core/commit/1da498156ae0c2e540d21ff267f807b30b8bb6e4 should allow using full filename in the worker.
But I couldn't reproduce the other part: js being required in noworker mode. Do you see this error with standalone version or on c9.io, and what path do you get in https://github.com/aisle-moz/moz.xliff/blob/master/plugin.js#L17?

**Comment by nightwing** [comment] 2015-04-17 23:08
@Pike The Issue with relative imports not working in main thread was fixed by https://github.com/c9/core/commit/bb5cfce7e9a1a67d926b97d30e6777235bb95f7a and followup commits.
Please let us know if you still see any issues with it.

**Closed as completed by nightwing** 2015-04-17 23:08 UTC
